import type { UserCard } from "./types";

export const sampleUsers: UserCard[] = [
  {
    id: "1",
    name: "Ava Chen",
    role: "Product Designer",
    department: "Design",
    email: "ava.chen@hexacards.io",
    phone: "+1 (415) 882-0142",
    location: "San Francisco",
    bio: "Crafts interaction systems that feel effortless on first tap.",
    initials: "AC",
    accent: "jade",
    status: "available",
  },
  {
    id: "2",
    name: "Marcus Reed",
    role: "Frontend Engineer",
    department: "Engineering",
    email: "marcus.reed@hexacards.io",
    phone: "+1 (628) 441-9033",
    location: "Austin",
    bio: "Builds performant UI primitives with a bias toward touch clarity.",
    initials: "MR",
    accent: "sky",
    status: "busy",
  },
  {
    id: "3",
    name: "Sofia Alvarez",
    role: "Brand Strategist",
    department: "Marketing",
    email: "sofia.alvarez@hexacards.io",
    phone: "+1 (312) 774-2201",
    location: "Chicago",
    bio: "Turns product moments into memorable brand experiences.",
    initials: "SA",
    accent: "amber",
    status: "available",
  },
  {
    id: "4",
    name: "Jonah Park",
    role: "Platform Lead",
    department: "Engineering",
    email: "jonah.park@hexacards.io",
    phone: "+1 (206) 555-0188",
    location: "Seattle",
    bio: "Keeps systems light, reliable, and ready for real devices.",
    initials: "JP",
    accent: "violet",
    status: "away",
  },
  {
    id: "5",
    name: "Nina Okonkwo",
    role: "UX Researcher",
    department: "Research",
    email: "nina.okonkwo@hexacards.io",
    phone: "+1 (617) 390-4410",
    location: "Boston",
    bio: "Validates every gesture against how people actually tap and hold.",
    initials: "NO",
    accent: "rose",
    status: "available",
  },
  {
    id: "6",
    name: "Eli Navarro",
    role: "Motion Designer",
    department: "Design",
    email: "eli.navarro@hexacards.io",
    phone: "+1 (503) 216-7780",
    location: "Portland",
    bio: "Designs micro-motion that guides attention without slowing you down.",
    initials: "EN",
    accent: "jade",
    status: "busy",
  },
];
