-- HexaCards — admin seed (default super admin)
-- Run AFTER schema.sql (admin table). Safe to re-run.
-- Login: admin@hexacards.com / superadmin123

create table if not exists public.admin (
  aid      bigint       generated by default as identity
           (start with 1 increment by 1) primary key,
  fname    varchar(100) not null default '',
  lname    varchar(100) not null default '',
  email    varchar(150) not null,
  mobile   varchar(20)  not null default '',
  password varchar(255) not null,
  profile  varchar(255),
  status   smallint     not null default 1 check (status in (0, 1)),
  constraint admin_email_unique unique (email)
);

insert into public.admin
  (aid, fname, lname, email, mobile, password, profile, status)
values
  (
    1,
    'Super',
    'Admin',
    'admin@hexacards.com',
    '9999999999',
    -- scrypt hash for: superadmin123
    'c7210879e0e4cbf6ee29ad205136bd0b:0a5546ef6395faf08f056fe6269e6098cbda0349c4e49d6f88cf95cc3522dde51c346cd584e6c1d1172b59eaabbd190b901841781e4ab14a7d0ac6805b1495e3',
    null,
    1
  )
on conflict (email) do update set
  fname    = excluded.fname,
  lname    = excluded.lname,
  mobile   = excluded.mobile,
  password = excluded.password,
  status   = excluded.status;

select setval(
  pg_get_serial_sequence('public.admin', 'aid'),
  (select coalesce(max(aid), 1) from public.admin)
);
