-- HexaCards — card_theme table + seed (layouts)
-- Run BEFORE creating cards that FK to theme_id, or after cards if adding FK later.
-- Safe to re-run.

create table if not exists public.card_theme (
  theme_id   integer      generated by default as identity
             (start with 1 increment by 1) primary key,
  theme_name varchar(100) not null,
  theme_path varchar(255) not null default '',
  status     smallint     not null default 1 check (status in (0, 1)),

  constraint card_theme_name_unique unique (theme_name)
);

create index if not exists card_theme_status_idx on public.card_theme (status);

insert into public.card_theme (theme_id, theme_name, theme_path, status)
values
  (1, 'Classic',    'classic',    1),
  (2, 'Basic',      'basic',      1),
  (3, 'Modern',     'modern',     1),
  (4, 'Compact',    'compact',    1),
  (5, 'Social',     'social',     1),
  (6, 'Minimalist', 'minimalist', 1)
on conflict (theme_id) do update set
  theme_name = excluded.theme_name,
  theme_path = excluded.theme_path,
  status     = excluded.status;

select setval(
  pg_get_serial_sequence('public.card_theme', 'theme_id'),
  (select coalesce(max(theme_id), 1) from public.card_theme)
);

alter table public.card_theme enable row level security;

drop policy if exists "Public read active card themes" on public.card_theme;
create policy "Public read active card themes"
  on public.card_theme for select
  using (status = 1);

-- Link cards.theme_id → card_theme (safe if cards already exists)
do $$
begin
  if exists (
    select 1 from information_schema.tables
    where table_schema = 'public' and table_name = 'cards'
  ) and not exists (
    select 1 from information_schema.table_constraints
    where table_schema = 'public'
      and table_name = 'cards'
      and constraint_name = 'cards_theme_id_fkey'
  ) then
    -- Ensure default theme rows exist before FK
    update public.cards set theme_id = 1 where theme_id is null or theme_id < 1;
    alter table public.cards
      add constraint cards_theme_id_fkey
      foreign key (theme_id) references public.card_theme (theme_id)
      on delete restrict;
  end if;
end $$;
