-- HexaCards — cards table (run if missing after an older schema.sql)
-- Requires: public.users, public.state, public.city, public.card_theme
-- Run card-theme-seed.sql first if card_theme is missing.

create table if not exists public.cards (
  card_id         bigint       generated by default as identity
                  (start with 1 increment by 1) primary key,
  unic_card_name  varchar(150) not null,
  card_name       varchar(150) not null default '',
  job_name        varchar(150) not null default '',
  business_name   varchar(255) not null default '',
  user_id         bigint       not null
                  references public.users (user_id) on delete cascade,
  logo            varchar(255),
  bg_img          varchar(255),
  bg_url          varchar(500),
  theme_id        integer      not null default 1
                  references public.card_theme (theme_id) on delete restrict,
  accent_color    varchar(32),
  mobile          varchar(20)  not null default '',
  email           varchar(255),
  website         varchar(500),
  code            varchar(10)  not null default '91',
  whatsapp        varchar(20),
  state_id        bigint       references public.state (state_id) on delete set null,
  city_id         bigint       references public.city (city_id) on delete set null,
  address         text,
  about           text,
  facebook_url    varchar(500),
  instagram_url   varchar(500),
  linkedin_url    varchar(500),
  twitter_url     varchar(500),
  youtube_url     varchar(500),
  google_url      varchar(500),
  about_company   text,
  services        text,
  brochure        varchar(500),
  page_view       bigint       not null default 0,
  start_date      date,
  end_date        date,
  date_time       timestamptz  not null default now(),
  update_time     timestamptz  not null default now(),
  status          smallint     not null default 1 check (status in (0, 1)),
  extra_mobiles   text         not null default '',

  constraint cards_unic_card_name_unique unique (unic_card_name)
);

create index if not exists cards_user_id_idx        on public.cards (user_id);
create index if not exists cards_unic_card_name_idx on public.cards (unic_card_name);
create index if not exists cards_status_idx         on public.cards (status);
create index if not exists cards_theme_id_idx       on public.cards (theme_id);
create index if not exists cards_state_id_idx       on public.cards (state_id);
create index if not exists cards_city_id_idx        on public.cards (city_id);
create index if not exists cards_date_time_idx      on public.cards (date_time desc);

create or replace function public.set_update_time()
returns trigger
language plpgsql
as $$
begin
  new.update_time = now();
  return new;
end;
$$;

drop trigger if exists cards_set_update_time on public.cards;
create trigger cards_set_update_time
  before update on public.cards
  for each row execute function public.set_update_time();

alter table public.cards enable row level security;

drop policy if exists "Public read active cards" on public.cards;
create policy "Public read active cards"
  on public.cards for select
  using (status = 1);
