-- HexaCards — migrate categories to new column layout
-- Run in Supabase SQL Editor AFTER schema.sql (or on DBs that still have
-- old columns: id / title / subtitle / image_src).
--
-- New shape (primary cols first):
--   category_id, category_name, category_desc, category_img,
--   then: slug, sort_order, status, created_at, updated_at
-- products.category_id becomes bigint FK → categories(category_id)
--
-- Note: Postgres forbids subqueries in ALTER … USING, so text→bigint
-- conversion uses a temporary column + JOIN update.

-- ── 1) Reshape categories if still on legacy columns ───────────────────────
do $$
declare
  has_old boolean;
  has_new boolean;
begin
  select exists (
    select 1 from information_schema.columns
    where table_schema = 'public'
      and table_name = 'categories'
      and column_name = 'title'
  ) into has_old;

  select exists (
    select 1 from information_schema.columns
    where table_schema = 'public'
      and table_name = 'categories'
      and column_name = 'category_id'
  ) into has_new;

  if has_new and not has_old then
    raise notice 'categories already migrated';
  elsif has_old then
    alter table if exists public.products
      drop constraint if exists products_category_id_fkey;

    drop table if exists public.categories_legacy cascade;
    alter table public.categories rename to categories_legacy;

    create table public.categories (
      category_id   bigint       generated by default as identity
                    (start with 1 increment by 1) primary key,
      category_name varchar(150) not null,
      category_desc text,
      category_img  varchar(255),
      slug          varchar(100) not null,
      sort_order    integer      not null default 0,
      status        smallint     not null default 1 check (status in (0, 1)),
      created_at    timestamptz  not null default now(),
      updated_at    timestamptz  not null default now(),
      constraint categories_slug_unique unique (slug)
    );

    insert into public.categories
      (category_name, category_desc, category_img, slug, sort_order, status, created_at, updated_at)
    select
      coalesce(nullif(trim(title), ''), id),
      nullif(trim(coalesce(subtitle, '')), ''),
      nullif(
        regexp_replace(trim(coalesce(image_src, '')), '^.+[\\/]', ''),
        ''
      ),
      id,
      coalesce(sort_order, 0),
      1,
      coalesce(created_at, now()),
      coalesce(updated_at, now())
    from public.categories_legacy
    order by coalesce(sort_order, 0), id;

    drop table public.categories_legacy;

    raise notice 'categories reshaped from legacy id/title/subtitle/image_src';
  else
    create table if not exists public.categories (
      category_id   bigint       generated by default as identity
                    (start with 1 increment by 1) primary key,
      category_name varchar(150) not null,
      category_desc text,
      category_img  varchar(255),
      slug          varchar(100) not null,
      sort_order    integer      not null default 0,
      status        smallint     not null default 1 check (status in (0, 1)),
      created_at    timestamptz  not null default now(),
      updated_at    timestamptz  not null default now(),
      constraint categories_slug_unique unique (slug)
    );
  end if;
end $$;

-- ── 2) products.category_id: text slug → bigint (temp column + JOIN) ─────
do $$
begin
  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public'
      and table_name = 'products'
      and column_name = 'category_id'
      and data_type in ('text', 'character varying')
  ) then
    alter table public.products
      drop constraint if exists products_category_id_fkey;

    alter table public.products
      drop column if exists category_id_new;

    alter table public.products
      add column category_id_new bigint;

    update public.products p
    set category_id_new = c.category_id
    from public.categories c
    where c.slug = p.category_id;

    alter table public.products drop column category_id;
    alter table public.products rename column category_id_new to category_id;

    raise notice 'products.category_id converted text → bigint';
  else
    raise notice 'products.category_id already bigint (or missing) — skip cast';
  end if;
end $$;

-- ── 3) FK + indexes (legacy category_id only; new shape uses product_category) ─
do $$
begin
  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public'
      and table_name = 'products'
      and column_name = 'category_id'
  ) and not exists (
    select 1 from information_schema.columns
    where table_schema = 'public'
      and table_name = 'products'
      and column_name = 'product_category'
  ) then
    alter table public.products
      drop constraint if exists products_category_id_fkey;

    alter table public.products
      add constraint products_category_id_fkey
      foreign key (category_id)
      references public.categories (category_id)
      on delete set null;

    create index if not exists products_category_id_idx on public.products (category_id);
  end if;
end $$;

create index if not exists categories_sort_order_idx on public.categories (sort_order);

-- ── 4) updated_at trigger ─────────────────────────────────────────────────
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists categories_set_updated_at on public.categories;
create trigger categories_set_updated_at
  before update on public.categories
  for each row execute function public.set_updated_at();

-- ── 5) Seed defaults (safe to re-run) ─────────────────────────────────────
insert into public.categories
  (category_id, category_name, category_desc, category_img, slug, sort_order, status)
values
  (1, 'Business Card', 'NFC, PVC, and metal card products.', 'digitalCard.jpg', 'business-card', 1, 1),
  (2, 'Digital Profile + QR', 'Print-ready QR cards that open your digital profile instantly.', 'digitalQR.jpg', 'digital-profile-qr', 2, 1),
  (3, 'Social Media Card', 'Google review, Instagram, YouTube, and keychain QR cards.', 'googleReview.jpg', 'social-media-card', 3, 1),
  (4, 'Standee', 'Google, Instagram, and YouTube review standees.', 'reviewStandy.jpg', 'standee', 4, 1)
on conflict (category_id) do update set
  category_name = excluded.category_name,
  category_desc = excluded.category_desc,
  category_img  = coalesce(
    nullif(regexp_replace(coalesce(public.categories.category_img, ''), '^.+[\\/]', ''), ''),
    excluded.category_img
  ),
  slug          = excluded.slug,
  sort_order    = excluded.sort_order,
  status        = excluded.status;

-- Store filename only (strip any folder path already saved)
update public.categories
set category_img = regexp_replace(category_img, '^.+[\\/]', '')
where category_img is not null
  and category_img ~ '[\\/]';

select setval(
  pg_get_serial_sequence('public.categories', 'category_id'),
  (select coalesce(max(category_id), 1) from public.categories)
);

alter table public.categories enable row level security;

drop policy if exists "Public read active categories" on public.categories;
create policy "Public read active categories"
  on public.categories for select
  using (status = 1);

drop policy if exists "Public read categories" on public.categories;
create policy "Public read categories"
  on public.categories for select
  using (true);
