-- HexaCards — links table (card social / brochure / website URLs)
-- Requires: public.cards
-- Run in Supabase SQL Editor after cards-table.sql
--
-- One row per link type per card. File/URL value only in link_url.
-- Types: website, facebook, instagram, linkedin, twitter, youtube,
--        google_review, telegram, snapchat, pinterest, tripadvisor, brochure

create table if not exists public.links (
  link_id      bigint       generated by default as identity
               (start with 1 increment by 1) primary key,
  card_id      bigint       not null
               references public.cards (card_id) on delete cascade,
  link_type    varchar(50)  not null,
  link_url     varchar(1000) not null default '',
  link_label   varchar(150),
  sort_order   integer      not null default 0,
  status       smallint     not null default 1 check (status in (0, 1)),
  date_time    timestamptz  not null default now(),
  update_time  timestamptz  not null default now(),

  constraint links_card_type_unique unique (card_id, link_type),
  constraint links_type_check check (
    link_type in (
      'website',
      'facebook',
      'instagram',
      'linkedin',
      'twitter',
      'youtube',
      'google_review',
      'telegram',
      'snapchat',
      'pinterest',
      'tripadvisor',
      'brochure'
    )
  )
);

create index if not exists links_card_id_idx on public.links (card_id);
create index if not exists links_type_idx on public.links (link_type);
create index if not exists links_status_idx on public.links (status);

-- Ensure update_time trigger helper exists (also created by cards-table.sql)
create or replace function public.set_update_time()
returns trigger
language plpgsql
as $$
begin
  new.update_time = now();
  return new;
end;
$$;

drop trigger if exists links_set_update_time on public.links;
create trigger links_set_update_time
  before update on public.links
  for each row execute function public.set_update_time();

alter table public.links enable row level security;

drop policy if exists "Public read active card links" on public.links;
create policy "Public read active card links"
  on public.links for select
  using (
    status = 1
    and exists (
      select 1 from public.cards c
      where c.card_id = links.card_id and c.status = 1
    )
  );

-- Migrate existing card link columns → links (idempotent upsert)
insert into public.links (card_id, link_type, link_url, sort_order, status)
select c.card_id, v.link_type, v.link_url, v.sort_order, 1
from public.cards c
cross join lateral (
  values
    ('website',       nullif(trim(c.website), ''),        10),
    ('facebook',      nullif(trim(c.facebook_url), ''),   20),
    ('instagram',     nullif(trim(c.instagram_url), ''),  30),
    ('linkedin',      nullif(trim(c.linkedin_url), ''),   40),
    ('twitter',       nullif(trim(c.twitter_url), ''),    50),
    ('youtube',       nullif(trim(c.youtube_url), ''),    60),
    ('google_review', nullif(trim(c.google_url), ''),     70),
    ('brochure',      nullif(trim(c.brochure), ''),       120)
) as v(link_type, link_url, sort_order)
where v.link_url is not null
on conflict (card_id, link_type) do update
  set link_url    = excluded.link_url,
      sort_order  = excluded.sort_order,
      update_time = now(),
      status      = 1;
