-- HexaCards — create state + city tables (run if they don't exist yet)
-- Requires: public.country already created and India seeded as country_id = 1
-- Safe to re-run.

create table if not exists public.state (
  state_id   bigint       generated by default as identity
             (start with 1 increment by 1) primary key,
  state_name varchar(100) not null,
  state_type varchar(50)  not null default 'State'
             check (state_type in ('State', 'Union Territory')),
  status     smallint     not null default 1 check (status in (0, 1)),
  country_id bigint       not null default 1
             references public.country (country_id) on delete restrict,

  constraint state_name_country_unique unique (country_id, state_name)
);

create index if not exists state_country_id_idx on public.state (country_id);
create index if not exists state_status_idx     on public.state (status);
create index if not exists state_name_idx       on public.state (state_name);

create table if not exists public.city (
  city_id   bigint       generated by default as identity
            (start with 1 increment by 1) primary key,
  city_name varchar(100) not null,
  state_id  bigint       not null
            references public.state (state_id) on delete cascade,
  status    smallint     not null default 1 check (status in (0, 1)),

  constraint city_name_state_unique unique (state_id, city_name)
);

create index if not exists city_state_id_idx on public.city (state_id);
create index if not exists city_status_idx   on public.city (status);
create index if not exists city_name_idx     on public.city (city_name);

alter table public.state enable row level security;
alter table public.city enable row level security;

drop policy if exists "Public read active states" on public.state;
create policy "Public read active states"
  on public.state for select
  using (status = 1);

drop policy if exists "Public read active cities" on public.city;
create policy "Public read active cities"
  on public.city for select
  using (status = 1);
