-- HexaCards — messages (leads from digital card "Leave a Message" form)
-- Powers User Dashboard → Messages
-- Run AFTER: users, cards (optional)

create table if not exists public.messages (
  -- primary (dashboard inbox fields)
  message_id     bigint        generated by default as identity
                 (start with 1 increment by 1) primary key,
  user_id        bigint        references public.users (user_id) on delete set null,
  name           varchar(200)  not null,
  email          varchar(150)  not null default '',
  phone          varchar(20)   not null default '',
  website        varchar(500)  not null default '',
  message        text          not null default '',
  is_read        smallint      not null default 0 check (is_read in (0, 1)),
  created_at     timestamptz   not null default now(),
  -- remaining
  owner_phone    varchar(20)   not null default '',  -- card owner (dashboard filter)
  card_id        bigint        references public.cards (card_id) on delete set null,
  card_slug      varchar(150),
  message_code   varchar(32)   not null,             -- public id e.g. MSG-12345678
  updated_at     timestamptz   not null default now(),

  constraint messages_message_code_unique unique (message_code)
);

create index if not exists messages_user_id_idx on public.messages (user_id);
create index if not exists messages_owner_phone_idx on public.messages (owner_phone);
create index if not exists messages_card_id_idx on public.messages (card_id);
create index if not exists messages_is_read_idx on public.messages (is_read);
create index if not exists messages_created_at_idx on public.messages (created_at desc);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists messages_set_updated_at on public.messages;
create trigger messages_set_updated_at
  before update on public.messages
  for each row execute function public.set_updated_at();

alter table public.messages enable row level security;

-- No public anon write policies — inserts go through Next.js API (service role).
