-- HexaCards — orders + order_items
-- Run AFTER: users, products, country/state/city, cards (optional FK)
-- If you already have the older orders shape, run orders-migrate.sql instead.
--
-- Primary columns (as specified) first, then remaining operational columns.

create table if not exists public.orders (
  -- ── primary columns ─────────────────────────────────────────────────────
  order_id             bigint         generated by default as identity
                       (start with 1 increment by 1) primary key,
  user_id              bigint         references public.users (user_id) on delete set null,
  product_id           bigint         references public.products (product_id) on delete set null,
  name                 varchar(200)   not null,
  mobile_number        varchar(20)    not null,
  designation          varchar(150)   not null default '',
  logo                 varchar(255),
  bungalow             varchar(255)   not null default '',
  street_name          varchar(255)   not null default '',
  landmark             varchar(255)   not null default '',
  pincode              varchar(20)    not null default '',
  city                 varchar(100)   not null default '',
  state                varchar(100)   not null default '',
  amount               numeric(10, 2) not null default 0.00,
  date                 date           not null default (current_date),
  -- status: 0=placed, 1=shipped, 2=delivered
  status               smallint       not null default 0 check (status in (0, 1, 2)),
  -- payment_status: 0=pending, 1=paid, 2=failed, 3=refunded
  payment_status       smallint       not null default 0 check (payment_status in (0, 1, 2, 3)),
  payment_method       varchar(50)    not null default '',
  delivery_charges     numeric(10, 2) not null default 0.00,
  ord_date             timestamptz    not null default now(),
  nimbus_pushed        smallint       not null default 0 check (nimbus_pushed in (0, 1)),
  awb_number           varchar(100),
  courier_name         varchar(100),
  shipment_created_at  timestamptz,

  -- ── remaining columns ───────────────────────────────────────────────────
  order_code           varchar(32)    not null,
  owner_phone          varchar(20)    not null default '',
  email                varchar(150)   not null default '',
  address              text           not null default '',
  pack_title           varchar(150)   not null default '',
  qty                  integer        not null default 1 check (qty > 0),
  subtotal             numeric(10, 2) not null default 0.00,
  discount             numeric(10, 2) not null default 0.00,
  coupon               varchar(50),
  country_id           bigint         references public.country (country_id) on delete set null,
  state_id             bigint         references public.state (state_id) on delete set null,
  city_id              bigint         references public.city (city_id) on delete set null,
  country_name         varchar(100)   not null default '',
  product_slug         varchar(100),
  product_title        varchar(255)   not null default '',
  card_id              bigint         references public.cards (card_id) on delete set null,
  card_slug            varchar(150),
  card_url             varchar(500),
  company_name         varchar(255)   not null default '',
  business_name        varchar(255)   not null default '',
  review_link          text,
  card_design          jsonb,
  created_at           timestamptz    not null default now(),
  updated_at           timestamptz    not null default now(),

  constraint orders_order_code_unique unique (order_code)
);

create table if not exists public.order_items (
  order_item_id     bigint        generated by default as identity
                    (start with 1 increment by 1) primary key,
  order_id          bigint        not null
                    references public.orders (order_id) on delete cascade,
  product_id        bigint        references public.products (product_id) on delete set null,
  product_slug      varchar(100),
  product_title     varchar(255)  not null default '',
  pack_title        varchar(150)  not null default '',
  qty               integer       not null default 1 check (qty > 0),
  unit_price        numeric(10, 2) not null default 0.00,
  line_total        numeric(10, 2) not null default 0.00,
  sort_order        integer       not null default 0,
  created_at        timestamptz   not null default now()
);

create index if not exists orders_user_id_idx on public.orders (user_id);
create index if not exists orders_mobile_number_idx on public.orders (mobile_number);
create index if not exists orders_owner_phone_idx on public.orders (owner_phone);
create index if not exists orders_status_idx on public.orders (status);
create index if not exists orders_payment_status_idx on public.orders (payment_status);
create index if not exists orders_ord_date_idx on public.orders (ord_date desc);
create index if not exists orders_product_id_idx on public.orders (product_id);
create index if not exists orders_awb_number_idx on public.orders (awb_number);
create index if not exists order_items_order_id_idx on public.order_items (order_id);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists orders_set_updated_at on public.orders;
create trigger orders_set_updated_at
  before update on public.orders
  for each row execute function public.set_updated_at();

alter table public.orders enable row level security;
alter table public.order_items enable row level security;
