-- HexaCards — reshape orders to primary-column layout
-- Run in Supabase SQL Editor if orders already exists with the older shape
-- (customer_name / phone / postal_code / total / …).
--
-- Primary cols first:
--   order_id, user_id, product_id, name, mobile_number, designation, logo,
--   bungalow, street_name, landmark, pincode, city, state, amount, date,
--   status, payment_status, payment_method, delivery_charges, ord_date,
--   nimbus_pushed, awb_number, courier_name, shipment_created_at
-- Then remaining operational columns.

do $$
declare
  has_legacy boolean;
  has_new boolean;
  r record;
begin
  select exists (
    select 1 from information_schema.columns
    where table_schema = 'public'
      and table_name = 'orders'
      and column_name = 'customer_name'
  ) into has_legacy;

  select exists (
    select 1 from information_schema.columns
    where table_schema = 'public'
      and table_name = 'orders'
      and column_name = 'mobile_number'
  ) into has_new;

  if has_new and not has_legacy then
    raise notice 'orders already on new column layout';
    return;
  end if;

  -- Recover from a previous failed run that left only orders_legacy
  if not exists (
    select 1 from information_schema.tables
    where table_schema = 'public' and table_name = 'orders'
  ) and exists (
    select 1 from information_schema.tables
    where table_schema = 'public' and table_name = 'orders_legacy'
  ) then
    alter table public.orders_legacy rename to orders;
    raise notice 'restored orders from orders_legacy after failed migrate';
  end if;

  if not exists (
    select 1 from information_schema.tables
    where table_schema = 'public' and table_name = 'orders'
  ) then
    raise notice 'orders table missing — run orders-table.sql';
    return;
  end if;

  -- Re-check columns after possible restore
  select exists (
    select 1 from information_schema.columns
    where table_schema = 'public'
      and table_name = 'orders'
      and column_name = 'customer_name'
  ) into has_legacy;

  select exists (
    select 1 from information_schema.columns
    where table_schema = 'public'
      and table_name = 'orders'
      and column_name = 'mobile_number'
  ) into has_new;

  if has_new and not has_legacy then
    raise notice 'orders already on new column layout';
    return;
  end if;

  -- Drop child FK so we can rebuild parent
  alter table if exists public.order_items
    drop constraint if exists order_items_order_id_fkey;

  drop table if exists public.orders_legacy cascade;
  alter table public.orders rename to orders_legacy;

  -- Renaming the table keeps constraint/index names — free them for the new table
  for r in
    select c.conname
    from pg_constraint c
    where c.conrelid = 'public.orders_legacy'::regclass
      and c.conname like 'orders_%'
  loop
    execute format(
      'alter table public.orders_legacy rename constraint %I to %I',
      r.conname,
      'legacy_' || r.conname
    );
  end loop;

  for r in
    select indexname
    from pg_indexes
    where schemaname = 'public'
      and tablename = 'orders_legacy'
      and indexname like 'orders_%'
  loop
    execute format(
      'alter index public.%I rename to %I',
      r.indexname,
      'legacy_' || r.indexname
    );
  end loop;

  create table public.orders (
    order_id             bigint         generated by default as identity
                         (start with 1 increment by 1) primary key,
    user_id              bigint         references public.users (user_id) on delete set null,
    product_id           bigint         references public.products (product_id) on delete set null,
    name                 varchar(200)   not null,
    mobile_number        varchar(20)    not null,
    designation          varchar(150)   not null default '',
    logo                 varchar(255),
    bungalow             varchar(255)   not null default '',
    street_name          varchar(255)   not null default '',
    landmark             varchar(255)   not null default '',
    pincode              varchar(20)    not null default '',
    city                 varchar(100)   not null default '',
    state                varchar(100)   not null default '',
    amount               numeric(10, 2) not null default 0.00,
    date                 date           not null default (current_date),
    status               smallint       not null default 0 check (status in (0, 1, 2)),
    payment_status       smallint       not null default 1 check (payment_status in (0, 1, 2, 3)),
    payment_method       varchar(50)    not null default '',
    delivery_charges     numeric(10, 2) not null default 0.00,
    ord_date             timestamptz    not null default now(),
    nimbus_pushed        smallint       not null default 0 check (nimbus_pushed in (0, 1)),
    awb_number           varchar(100),
    courier_name         varchar(100),
    shipment_created_at  timestamptz,
    order_code           varchar(32)    not null,
    owner_phone          varchar(20)    not null default '',
    email                varchar(150)   not null default '',
    address              text           not null default '',
    pack_title           varchar(150)   not null default '',
    qty                  integer        not null default 1 check (qty > 0),
    subtotal             numeric(10, 2) not null default 0.00,
    discount             numeric(10, 2) not null default 0.00,
    coupon               varchar(50),
    country_id           bigint         references public.country (country_id) on delete set null,
    state_id             bigint         references public.state (state_id) on delete set null,
    city_id              bigint         references public.city (city_id) on delete set null,
    country_name         varchar(100)   not null default '',
    product_slug         varchar(100),
    product_title        varchar(255)   not null default '',
    card_id              bigint         references public.cards (card_id) on delete set null,
    card_slug            varchar(150),
    card_url             varchar(500),
    company_name         varchar(255)   not null default '',
    business_name        varchar(255)   not null default '',
    review_link          text,
    card_design          jsonb,
    created_at           timestamptz    not null default now(),
    updated_at           timestamptz    not null default now(),
    constraint orders_order_code_unique unique (order_code)
  );

  insert into public.orders (
    order_id, user_id, product_id, name, mobile_number, designation, logo,
    bungalow, street_name, landmark, pincode, city, state, amount, date,
    status, payment_status, payment_method, delivery_charges, ord_date,
    nimbus_pushed, awb_number, courier_name, shipment_created_at,
    order_code, owner_phone, email, address, pack_title, qty, subtotal,
    discount, coupon, country_id, state_id, city_id, country_name,
    product_slug, product_title, card_id, card_slug, card_url,
    company_name, business_name, review_link, card_design,
    created_at, updated_at
  )
  select
    order_id,
    user_id,
    product_id,
    coalesce(nullif(trim(customer_name), ''), 'Customer'),
    coalesce(nullif(trim(phone), ''), nullif(trim(owner_phone), ''), ''),
    coalesce(job_title, ''),
    order_logo,
    coalesce(nullif(trim(address), ''), ''),
    '',
    '',
    coalesce(postal_code, ''),
    coalesce(city_name, ''),
    coalesce(state_name, ''),
    coalesce(total, 0),
    coalesce(created_at::date, current_date),
    coalesce(status, 0),
    coalesce(payment_status, 1),
    '',
    0,
    coalesce(created_at, now()),
    0,
    null,
    null,
    null,
    order_code,
    coalesce(owner_phone, ''),
    coalesce(email, ''),
    coalesce(address, ''),
    coalesce(pack_title, ''),
    coalesce(qty, 1),
    coalesce(subtotal, 0),
    coalesce(discount, 0),
    coupon,
    country_id,
    state_id,
    city_id,
    coalesce(country_name, ''),
    product_slug,
    coalesce(product_title, ''),
    card_id,
    card_slug,
    card_url,
    coalesce(company_name, ''),
    coalesce(business_name, ''),
    review_link,
    card_design,
    coalesce(created_at, now()),
    coalesce(updated_at, now())
  from public.orders_legacy
  order by order_id;

  -- Preserve identity sequence
  perform setval(
    pg_get_serial_sequence('public.orders', 'order_id'),
    (select coalesce(max(order_id), 1) from public.orders)
  );

  -- Re-link order_items
  alter table public.order_items
    add constraint order_items_order_id_fkey
    foreign key (order_id) references public.orders (order_id) on delete cascade;

  drop table public.orders_legacy;

  raise notice 'orders reshaped to primary column layout';
end $$;

create index if not exists orders_user_id_idx on public.orders (user_id);
create index if not exists orders_mobile_number_idx on public.orders (mobile_number);
create index if not exists orders_owner_phone_idx on public.orders (owner_phone);
create index if not exists orders_status_idx on public.orders (status);
create index if not exists orders_payment_status_idx on public.orders (payment_status);
create index if not exists orders_ord_date_idx on public.orders (ord_date desc);
create index if not exists orders_product_id_idx on public.orders (product_id);
create index if not exists orders_awb_number_idx on public.orders (awb_number);

drop trigger if exists orders_set_updated_at on public.orders;
create trigger orders_set_updated_at
  before update on public.orders
  for each row execute function public.set_updated_at();

alter table public.orders enable row level security;
alter table public.order_items enable row level security;
