-- HexaCards — payments (Razorpay / UPI gateway records)
-- Run AFTER: users, orders
-- Example row:
--   id=157, client_txn_id=675a7506e3525, amount=100, customer_id=373,
--   gateway_order_id=order_PW9MzrGOpqQvYm, status=success,
--   upi_txn_id=pay_PW9N9AjoawVhgf, order_id=799

create table if not exists public.payments (
  id                   bigint         generated by default as identity
                       (start with 1 increment by 1) primary key,
  client_txn_id        varchar(64)    not null,
  amount               numeric(10, 2) not null default 0.00,
  customer_id          bigint         references public.users (user_id) on delete set null,
  gateway_order_id     varchar(100),
  created_at           timestamptz    not null default now(),
  txn_at               timestamptz,
  remark               text,
  -- e.g. success | pending | failed | refunded
  status               varchar(30)    not null default 'pending',
  upi_txn_id           varchar(100),
  razorpay_payment_id  varchar(100),
  order_id             bigint         references public.orders (order_id) on delete set null,

  constraint payments_client_txn_id_unique unique (client_txn_id)
);

create index if not exists payments_customer_id_idx on public.payments (customer_id);
create index if not exists payments_order_id_idx on public.payments (order_id);
create index if not exists payments_status_idx on public.payments (status);
create index if not exists payments_gateway_order_id_idx on public.payments (gateway_order_id);
create index if not exists payments_razorpay_payment_id_idx on public.payments (razorpay_payment_id);
create index if not exists payments_created_at_idx on public.payments (created_at desc);

alter table public.payments enable row level security;

-- No public anon policies — service role / API only (payment PII).
