-- HexaCards — migrate products to new column layout
-- Run AFTER categories-migrate.sql (categories must use category_id).
--
-- New shape (primary cols first):
--   product_id, product_name, product_category, product_desc, product_img,
--   product_price, regular_price,
--   then: slug, short_title, category, media, highlights, finishes, included,
--         cta_*, designable, sort_order, active, timestamps
-- product_img = filename only (e.g. digitalCard.jpg)

do $$
declare
  has_legacy boolean;
  has_new boolean;
  fallback_cat bigint;
begin
  select exists (
    select 1 from information_schema.columns
    where table_schema = 'public'
      and table_name = 'products'
      and column_name = 'title'
  ) into has_legacy;

  select exists (
    select 1 from information_schema.columns
    where table_schema = 'public'
      and table_name = 'products'
      and column_name = 'product_id'
  ) into has_new;

  if has_new and not has_legacy then
    raise notice 'products already migrated';
    return;
  end if;

  if not has_legacy then
    -- Fresh create (schema may have skipped if table missing)
    create table if not exists public.products (
      product_id       bigint       generated by default as identity
                       (start with 1 increment by 1) primary key,
      product_name     varchar(255) not null,
      product_category bigint       not null
                       references public.categories (category_id) on delete restrict,
      product_desc     text,
      product_img      varchar(255),
      product_price    numeric(10, 2) not null default 0.00,
      regular_price    numeric(10, 2) not null default 0.00,
      slug             varchar(100) not null,
      short_title      varchar(255) not null default '',
      category         text         not null default 'General',
      media            jsonb        not null default '[]'::jsonb,
      highlights       jsonb        not null default '[]'::jsonb,
      finishes         jsonb        not null default '[]'::jsonb,
      included         jsonb        not null default '[]'::jsonb,
      cta_label        text         not null default 'Order Now',
      cta_href         text         not null default '',
      designable       boolean      not null default false,
      sort_order       integer      not null default 0,
      active           boolean      not null default true,
      created_at       timestamptz  not null default now(),
      updated_at       timestamptz  not null default now(),
      constraint products_slug_unique unique (slug)
    );
    raise notice 'products table created (fresh)';
    return;
  end if;

  select coalesce(min(category_id), 1) into fallback_cat from public.categories;

  alter table if exists public.products
    drop constraint if exists products_category_id_fkey;
  alter table if exists public.products
    drop constraint if exists products_product_category_fkey;

  drop table if exists public.products_legacy cascade;
  alter table public.products rename to products_legacy;

  create table public.products (
    product_id       bigint       generated by default as identity
                     (start with 1 increment by 1) primary key,
    product_name     varchar(255) not null,
    product_category bigint       not null
                     references public.categories (category_id) on delete restrict,
    product_desc     text,
    product_img      varchar(255),
    product_price    numeric(10, 2) not null default 0.00,
    regular_price    numeric(10, 2) not null default 0.00,
    slug             varchar(100) not null,
    short_title      varchar(255) not null default '',
    category         text         not null default 'General',
    media            jsonb        not null default '[]'::jsonb,
    highlights       jsonb        not null default '[]'::jsonb,
    finishes         jsonb        not null default '[]'::jsonb,
    included         jsonb        not null default '[]'::jsonb,
    cta_label        text         not null default 'Order Now',
    cta_href         text         not null default '',
    designable       boolean      not null default false,
    sort_order       integer      not null default 0,
    active           boolean      not null default true,
    created_at       timestamptz  not null default now(),
    updated_at       timestamptz  not null default now(),
    constraint products_slug_unique unique (slug)
  );

  insert into public.products (
    product_name,
    product_category,
    product_desc,
    product_img,
    product_price,
    regular_price,
    slug,
    short_title,
    category,
    media,
    highlights,
    finishes,
    included,
    cta_label,
    cta_href,
    designable,
    sort_order,
    active,
    created_at,
    updated_at
  )
  select
    coalesce(nullif(trim(title), ''), id),
    coalesce(category_id, fallback_cat),
    nullif(trim(coalesce(description, '')), ''),
    nullif(
      regexp_replace(trim(coalesce(image_src, '')), '^.+[\\/]', ''),
      ''
    ),
    coalesce(price, 0),
    coalesce(compare_at_price, 0),
    id,
    coalesce(nullif(trim(short_title), ''), title, id),
    coalesce(nullif(trim(category), ''), 'General'),
    coalesce(media, '[]'::jsonb),
    coalesce(highlights, '[]'::jsonb),
    coalesce(finishes, '[]'::jsonb),
    coalesce(included, '[]'::jsonb),
    coalesce(nullif(trim(cta_label), ''), 'Order Now'),
    coalesce(cta_href, ''),
    coalesce(designable, false),
    coalesce(sort_order, 0),
    coalesce(active, true),
    coalesce(created_at, now()),
    coalesce(updated_at, now())
  from public.products_legacy
  order by coalesce(sort_order, 0), id;

  drop table public.products_legacy;

  raise notice 'products reshaped to product_id / product_name / …';
end $$;

create index if not exists products_product_category_idx
  on public.products (product_category);
create index if not exists products_sort_order_idx
  on public.products (sort_order);

-- filename-only cleanup (if already new shape with paths)
update public.products
set product_img = regexp_replace(product_img, '^.+[\\/]', '')
where product_img is not null
  and product_img ~ '[\\/]';

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists products_set_updated_at on public.products;
create trigger products_set_updated_at
  before update on public.products
  for each row execute function public.set_updated_at();

alter table public.products enable row level security;

drop policy if exists "Public read active products" on public.products;
create policy "Public read active products"
  on public.products for select
  using (active = true);

drop policy if exists "Public read products" on public.products;
create policy "Public read products"
  on public.products for select
  using (true);

select setval(
  pg_get_serial_sequence('public.products', 'product_id'),
  (select coalesce(max(product_id), 1) from public.products)
);
