-- HexaCards — product reviews
-- Run AFTER: users, products
-- Columns match source dump: review_id, user_id, product_id, review_text, rating_value

create table if not exists public.reviews (
  review_id     bigint       generated by default as identity
                (start with 1 increment by 1) primary key,
  user_id       bigint       references public.users (user_id) on delete set null,
  product_id    bigint       references public.products (product_id) on delete cascade,
  review_text   text         not null default '',
  rating_value  smallint     not null default 0
                check (rating_value >= 0 and rating_value <= 5),
  created_at    timestamptz  not null default now(),
  updated_at    timestamptz  not null default now()
);

create index if not exists reviews_user_id_idx on public.reviews (user_id);
create index if not exists reviews_product_id_idx on public.reviews (product_id);
create index if not exists reviews_rating_value_idx on public.reviews (rating_value);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists reviews_set_updated_at on public.reviews;
create trigger reviews_set_updated_at
  before update on public.reviews
  for each row execute function public.set_updated_at();

alter table public.reviews enable row level security;

drop policy if exists "Public read reviews" on public.reviews;
create policy "Public read reviews"
  on public.reviews for select
  using (true);
