-- HexaCards — Super Admin Categories + Products
-- Run this in Supabase: SQL Editor → New query → Run

create extension if not exists "pgcrypto";

-- ── Categories (super-admin product sections) ───────────────────────────────
create table if not exists public.categories (
  id text primary key,
  title text not null,
  subtitle text not null default '',
  image_src text,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- ── Products ────────────────────────────────────────────────────────────────
create table if not exists public.products (
  id text primary key,
  category_id text references public.categories (id) on delete set null,
  category text not null default 'General',
  title text not null,
  short_title text not null,
  description text not null default '',
  price numeric(12, 2) not null default 0,
  compare_at_price numeric(12, 2) not null default 0,
  media jsonb not null default '[]'::jsonb,
  highlights jsonb not null default '[]'::jsonb,
  finishes jsonb not null default '[]'::jsonb,
  included jsonb not null default '[]'::jsonb,
  cta_label text not null default 'Order Now',
  cta_href text not null default '',
  designable boolean not null default false,
  image_src text,
  sort_order integer not null default 0,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists products_category_id_idx on public.products (category_id);
create index if not exists products_sort_order_idx on public.products (sort_order);
create index if not exists categories_sort_order_idx on public.categories (sort_order);

-- ── Country (ISO + phone codes) ─────────────────────────────────────────────
-- Matches classic country table: India = country_id 1 (project default).
-- After creating this table, run: frontend/sql/country-seed.sql
create table if not exists public.country (
  country_id   bigint       generated by default as identity
               (start with 1 increment by 1) primary key,
  iso          varchar(2)   not null,
  country_name varchar(100) not null,
  nicename     varchar(100) not null,
  iso3         varchar(3),
  numcode      integer,
  phonecode    integer      not null default 0,
  status       smallint     not null default 1 check (status in (0, 1)),

  constraint country_iso_unique unique (iso)
);

create index if not exists country_nicename_idx  on public.country (nicename);
create index if not exists country_phonecode_idx on public.country (phonecode);
create index if not exists country_status_idx    on public.country (status);

-- ── Users (login / OTP) ─────────────────────────────────────────────────────
-- user_id is numeric and sequential: 1, 2, 3, 4, ...
-- Drop old shape (uuid or old column set) before recreating.
drop table if exists public.users cascade;

create table public.users (
  -- ── Identity ──────────────────────────────────────────────────────────────
  user_id     bigint                    generated by default as identity
              (start with 1 increment by 1) primary key,

  -- ── Profile ───────────────────────────────────────────────────────────────
  first_name  varchar(100)              not null default '',
  last_name   varchar(100)              not null default '',
  mobile      varchar(20)               not null,
  email       varchar(150),
  password    varchar(255),

  -- ── Audit ─────────────────────────────────────────────────────────────────
  created_by  bigint                    references public.users (user_id) on delete set null,
  date_time   timestamptz               not null default now(),
  update_time timestamptz               not null default now(),

  -- ── Flags (0 = No, 1 = Yes) ───────────────────────────────────────────────
  is_mobile   smallint                  not null default 0 check (is_mobile   in (0,1)),
  is_email    smallint                  not null default 0 check (is_email    in (0,1)),
  status      smallint                  not null default 1 check (status      in (0,1)),

  -- ── OTP (appended at end as requested) ────────────────────────────────────
  otp         varchar(6),
  otp_expiry  timestamptz,

  -- ── Constraints ───────────────────────────────────────────────────────────
  constraint users_mobile_unique unique (mobile)
);

create index if not exists users_mobile_idx    on public.users (mobile);
create index if not exists users_email_idx     on public.users (email);
create index if not exists users_status_idx    on public.users (status);
create index if not exists users_date_time_idx on public.users (date_time desc);

-- ── User sessions (created after successful OTP login) ───────────────────────
create table if not exists public.user_session (
  id            bigint       generated by default as identity
                (start with 1 increment by 1) primary key,
  session_id    varchar(255) not null default gen_random_uuid()::text,
  session_token text         not null,
  datetime      timestamptz  not null default now(),
  -- who owns this session
  user_id       bigint       not null references public.users (user_id) on delete cascade,

  constraint user_session_session_id_unique    unique (session_id),
  constraint user_session_session_token_unique unique (session_token)
);

create index if not exists user_session_user_id_idx  on public.user_session (user_id);
create index if not exists user_session_token_idx    on public.user_session (session_token);
create index if not exists user_session_datetime_idx on public.user_session (datetime desc);

-- Auto-update updated_at
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- update_time auto-maintained
create or replace function public.set_update_time()
returns trigger
language plpgsql
as $$
begin
  new.update_time = now();
  return new;
end;
$$;

drop trigger if exists users_set_update_time on public.users;
create trigger users_set_update_time
  before update on public.users
  for each row execute function public.set_update_time();

drop trigger if exists categories_set_updated_at on public.categories;
create trigger categories_set_updated_at
  before update on public.categories
  for each row execute function public.set_updated_at();

drop trigger if exists products_set_updated_at on public.products;
create trigger products_set_updated_at
  before update on public.products
  for each row execute function public.set_updated_at();

-- Seed default categories (safe to re-run)
insert into public.categories (id, title, subtitle, image_src, sort_order)
values
  (
    'business-card',
    'Business Card',
    'NFC, PVC, and metal card products.',
    '/Images/Products/digitalCard.jpg',
    1
  ),
  (
    'digital-profile-qr',
    'Digital Profile + QR',
    'Print-ready QR cards that open your digital profile instantly.',
    '/Images/Products/digitalQR.jpg',
    2
  ),
  (
    'social-media-card',
    'Social Media Card',
    'Google review, Instagram, YouTube, and keychain QR cards.',
    '/Images/Products/googleReview.jpg',
    3
  ),
  (
    'standee',
    'Standee',
    'Google, Instagram, and YouTube review standees.',
    '/Images/Products/reviewStandy.jpg',
    4
  )
on conflict (id) do update set
  title = excluded.title,
  subtitle = excluded.subtitle,
  image_src = coalesce(public.categories.image_src, excluded.image_src),
  sort_order = excluded.sort_order;

-- RLS: enable + allow service role full access; anon read for public catalog later
alter table public.categories enable row level security;
alter table public.products enable row level security;
alter table public.users enable row level security;
alter table public.user_session enable row level security;
alter table public.country enable row level security;

drop policy if exists "Public read categories" on public.categories;
create policy "Public read categories"
  on public.categories for select
  using (true);

drop policy if exists "Public read active products" on public.products;
create policy "Public read active products"
  on public.products for select
  using (active = true);

drop policy if exists "Public read active countries" on public.country;
create policy "Public read active countries"
  on public.country for select
  using (status = 1);

-- User / session rows are accessed only through Next.js API (service role).
-- Country seed: run frontend/sql/country-seed.sql after this file.