-- HexaCards — India state / UT seed
-- Matches provided list (1–25) + remaining states (26–37). India = country_id 1.
-- Prerequisites: country table + India (country_id=1). Prefer running location-tables.sql first.
-- Safe to re-run.

create table if not exists public.state (
  state_id   bigint       generated by default as identity
             (start with 1 increment by 1) primary key,
  state_name varchar(100) not null,
  state_type varchar(50)  not null default 'State'
             check (state_type in ('State', 'Union Territory')),
  status     smallint     not null default 1 check (status in (0, 1)),
  country_id bigint       not null default 1
             references public.country (country_id) on delete restrict,
  constraint state_name_country_unique unique (country_id, state_name)
);

insert into public.state
  (state_id, state_name, state_type, status, country_id)
values
  (1,  'Andaman Nicobar',    'Union Territory', 1, 1),
  (2,  'Andhra Pradesh',     'State',           1, 1),
  (3,  'Arunachal Pradesh',  'State',           1, 1),
  (4,  'Assam',              'State',           1, 1),
  (5,  'Bihar',              'State',           1, 1),
  (6,  'Chandigarh',         'Union Territory', 1, 1),
  (7,  'Chhattisgarh',       'State',           1, 1),
  (8,  'Dadra Nagar Haveli', 'Union Territory', 1, 1),
  (9,  'Daman Diu',          'Union Territory', 1, 1),
  (10, 'Delhi',              'Union Territory', 1, 1),
  (11, 'Goa',                'State',           1, 1),
  (12, 'Gujarat',            'State',           1, 1),
  (13, 'Haryana',            'State',           1, 1),
  (14, 'Himachal Pradesh',   'State',           1, 1),
  (15, 'Jammu Kashmir',      'Union Territory', 1, 1),
  (16, 'Jharkhand',          'State',           1, 1),
  (17, 'Karnataka',          'State',           1, 1),
  (18, 'Kerala',             'State',           1, 1),
  (19, 'Ladakh',             'Union Territory', 1, 1),
  (20, 'Lakshadweep',        'Union Territory', 1, 1),
  (21, 'Madhya Pradesh',     'State',           1, 1),
  (22, 'Maharashtra',        'State',           1, 1),
  (23, 'Manipur',            'State',           1, 1),
  (24, 'Meghalaya',          'State',           1, 1),
  (25, 'Mizoram',            'State',           1, 1),
  (26, 'Nagaland',           'State',           1, 1),
  (27, 'Odisha',             'State',           1, 1),
  (28, 'Puducherry',         'Union Territory', 1, 1),
  (29, 'Punjab',             'State',           1, 1),
  (30, 'Rajasthan',          'State',           1, 1),
  (31, 'Sikkim',             'State',           1, 1),
  (32, 'Tamil Nadu',         'State',           1, 1),
  (33, 'Telangana',          'State',           1, 1),
  (34, 'Tripura',            'State',           1, 1),
  (35, 'Uttar Pradesh',      'State',           1, 1),
  (36, 'Uttarakhand',        'State',           1, 1),
  (37, 'West Bengal',        'State',           1, 1)
on conflict (state_id) do update set
  state_name = excluded.state_name,
  state_type = excluded.state_type,
  status     = excluded.status,
  country_id = excluded.country_id;

select setval(
  pg_get_serial_sequence('public.state', 'state_id'),
  (select coalesce(max(state_id), 1) from public.state)
);
